default:
  image:
    name: qao.physik.uni-kl.de:5000/qao-minimal:latest
    entrypoint: ["/bin/bash", "-l", "-c"]

stages:
  - test
  - build

test:
  stage: test
  tags:
    - python
  script:
    - "virtualenv --system-site-packages myapp"
    - "source myapp/bin/activate"
    - "pip install -r requirements.txt"
    - "python setup.py install"
    - "cd tests"
    - "pytest"

build:
  stage: build
  tags:
    - python
  script:
    - "virtualenv --system-site-packages myapp"
    - "source myapp/bin/activate"
    - "pip install -r requirements.txt"
    - "python setup.py install"
