stages:
  - test
  - deploy

test:
  type: test
  tags:
    - python
  script:
    - "virtualenv --system-site-packages myapp"
    - "source myapp/bin/activate"
    - "pip install -r requirements.txt"
    - "python setup.py install"
    - "cd tests"
    - "pytest"

  build:
    type: deploy
    tags:
      - python
    script:
      - "virtualenv --system-site-packages myapp"
      - "source myapp/bin/activate"
      - "pip install -r requirements.txt"
      - "python setup.py install"
