stages:
  - test
  - build

test:
  type: test
  tags:
    - python
  script:
    - "virtualenv --system-site-packages myapp"
    - "source myapp/bin/activate"
    - "pip install -r requirements.txt"
    - "python setup.py install"
    - "cd tests"
    - "pytest"

build:
  type: build
  tags:
    - python
  script:
    - "virtualenv --system-site-packages myapp"
    - "source myapp/bin/activate"
    - "pip install -r requirements.txt"
    - "python setup.py install"
